require( 'dotenv' ).config();

var User = require( './backend/models/user' );
const express = require( "express" );
const course = require( "./backend/controllers/course" );
const db = require( "./backend/db/connect" );
const config = require( "./backend/config/config" );
var authRouter = require( './backend/routes/auth' );
var session = require( 'express-session' );
const MongoStore = require( 'connect-mongo' );
var path = require( 'path' );
var cookieParser = require( 'cookie-parser' );
var logger = require( 'morgan' );
var cors = require( 'cors' );

const app = express();

//db.connect();

app.listen( config.webPort, function ()
{
    console.log( 'Server started at  http://localhost:' + config.webPort )
} );
app.use( cors() );
app.use( logger( 'dev' ) );
app.use( express.static( __dirname + '/frontend' ) );
app.use( express.json() );
app.use( express.urlencoded( {extended: true} ) );
app.use( cookieParser() );
// app.use( session( {
//     resave: false,
//     saveUninitialized: false,
//     secret: process.env.SESSION_SECRET,
//     store: MongoStore.create( {mongoUrl: process.env.MONGO_CONNECTION_STRING} )
// } ) );

app.get( "/", function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/tambola.html" );
} );

app.get( "/resume", function ( req, res )
{
    res.sendFile( __dirname + '/frontend/html/resume.html' );
} );

app.get( "/google", function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/googlesearch.html" );
} );

app.get( "/colors", function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/colors.html" );
} );
app.get( "/login", function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/login.html" );
} );

app.get( "/register", function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/register.html" );
} );
app.get( "/test", function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/test.html" );
} );

app.get( "/todo", function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/todoapi.html" );
} );


var todos = [];

app.get( '/api/todos', function ( req, res )
{
    // Get all todos
    res.send( JSON.stringify( todos ) );
} );

app.get( '/api/todos/:todoId', function ( req, res )
{
    // req.params.todoId
    // get single todo with given id

    for ( let i = 0; i < todos.length; i++ )
    {
        if ( todos[i].todoId == req.params.todoId )
            res.send( todos[i] );
    }
    res.sendStatus( 404 );
} );

app.put( '/api/todos/:todoId', function ( req, res )
{
    // update
    for ( let i = 0; i < todos.length; i++ )
    {
        if ( todos[i].todoId == req.params.todoId )
        {
            todos[i] = req.body;
            return;
        }
    }
    todos.push( req.body );
} );

app.delete( '/api/todos/:todoId', function ( req, res )
{
    // delete
    for ( let i = 0; i < todos.length; i++ )
    {
        if ( todos[i].todoId == req.params.todoId )
        {
            todos.splice( i, 1 );
            res.sendStatus( 200 );
            return;
        }
    }
    res.sendStatus( 404 );
} );


app.post( '/api/todos', function ( req, res )
{
    // Create
    // req.body will have what frontend sent
    todos.push( req.body );
} );

app.get( '/crud', function ( req, res )
{
    res.sendFile( __dirname + '/frontend/html/crud.html' );
} );


app.get( '/api/crud', function ( req, res )
{
    course.getallcourses( function ( err, courseobj )
    {
        res.json( courseobj );
    } );
} );

app.put( '/api/crud/:id', function ( req, res )
{
    req.body.Articels = parseInt( req.body.Articels );
    console.log( "Got PUT Req" );
    course.updatecourse( req.params.id, req.body, function ( err, courseobj )
    {
        if ( err )
            console.log( err );

        res.json( courseobj );
    } );
} );

app.delete( '/api/crud/:id', function ( req, res )
{
    console.log( req.params.id );
    course.deletecourse( req.params.id, function ( err, courseobj )
    {
        res.json( courseobj );
    } )
} );

app.post( '/api/crud', function ( req, res )
{
    course.createcourse( req.body );
    res.redirect( "/crud" );
} );

app.get( '/tambola', function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/tambola.html" );
} );

app.get( '/register', function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/register.html" )
} );


app.post( '/dashboard', function ( req, res )
{
    res.sendFile( __dirname + "/frontend/html/dashboard.html" )
} );

app.use( '/auth', authRouter );


app.use( '/mail', ( req, res ) =>
{
    if ( req.session && req.session.user )
    {
        var username = req.session.user.username;
        User.findOne( {name: username}, ( err, userobj ) =>
        {
            if ( err )
                res.send( err );
            if ( userobj )
                res.json( {success: true, email: userobj.email} );
            else
                res.json( {success: false} );
        } );

    }
    else
        res.json( {success: false} );
} );

app.get( '/dummy1', ( req, res ) =>
{
    res.json( [
        {"problemName": "SALARY", "problemLink": "https://www.stopstalk.com/problems?problem_id=19287", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "total_submissions":124, "solved":89},
        {"problemName": "STRNO", "problemLink": "https://www.stopstalk.com/problems?problem_id=70268", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "total_submissions":432, "solved":345},
        {"problemName": "XXXXX", "problemLink": "https://www.stopstalk.com/problems?problem_id=75554", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "total_submissions":213 , "solved":132},
        {"problemName": "Combinations", "problemLink": "https://www.stopstalk.com/problems?problem_id=28645", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "total_submissions":454,"solved":372},
        {"problemName": "Pi", "problemLink": "https://www.stopstalk.com/problems?problem_id=28617", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "total_submissions":234,"solved":211},
        {"problemName": "Bear and Finding Criminals", "problemLink": "https://www.stopstalk.com/problems?problem_id=15826", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "total_submissions":212,"solved":112},
    ]
    );
} );

app.get( '/dummy', ( req, res ) =>
{
    res.json( [
        {"problemName": "SALARY", "problemLink": "https://www.stopstalk.com/problems?problem_id=19287", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "* zanam *", "authorHandle": "https://www.stopstalk.com/user/profile/zanam", "addedOn": "2021-04-24 13:01:36", "votes": "3", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1809"},
        {"problemName": "STRNO", "problemLink": "https://www.stopstalk.com/problems?problem_id=70268", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "* zanam *", "authorHandle": "https://www.stopstalk.com/user/profile/zanam", "addedOn": "2021-04-24 12:08:42", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1808"},
        {"problemName": "XXXXX", "problemLink": "https://www.stopstalk.com/problems?problem_id=75554", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "* zanam *", "authorHandle": "https://www.stopstalk.com/user/profile/zanam", "addedOn": "2021-04-24 11:17:36", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1807"},
        {"problemName": "Combinations", "problemLink": "https://www.stopstalk.com/problems?problem_id=28645", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Md. Joynal Alam", "authorHandle": "https://www.stopstalk.com/user/profile/Joynal", "addedOn": "2021-03-05 09:38:07", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1803"},
        {"problemName": "Pi", "problemLink": "https://www.stopstalk.com/problems?problem_id=28617", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Md. Joynal Alam", "authorHandle": "https://www.stopstalk.com/user/profile/Joynal", "addedOn": "2021-03-05 09:31:51", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1801"},
        {"problemName": "Bear and Finding Criminals", "problemLink": "https://www.stopstalk.com/problems?problem_id=15826", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Md. Joynal Alam", "authorHandle": "https://www.stopstalk.com/user/profile/Joynal", "addedOn": "2021-03-02 20:38:41", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1800"},
        {"problemName": "Sherlock and Permutations", "problemLink": "https://www.stopstalk.com/problems?problem_id=19404", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "NULL NULL", "authorHandle": "https://www.stopstalk.com/user/profile/call_me_bishal", "addedOn": "2021-02-13 16:52:39", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1799"},
        {"problemName": "Make Them Odd", "problemLink": "https://www.stopstalk.com/problems?problem_id=62287", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Habib Hasan Shakil", "authorHandle": "https://www.stopstalk.com/user/profile/Habib_Hasan_Shakil", "addedOn": "2021-02-05 04:53:31", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1796"},
        {"problemName": "B. Frog 2", "problemLink": "https://www.stopstalk.com/problems?problem_id=72917", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/atcoder_small.png?_rev=None", "authorName": "Suraj Singh Sinsinwar", "authorHandle": "https://www.stopstalk.com/user/profile/suraj279", "addedOn": "2020-12-20 09:54:27", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1795"},
        {"problemName": "A. Frog 1", "problemLink": "https://www.stopstalk.com/problems?problem_id=72918", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/atcoder_small.png?_rev=None", "authorName": "Suraj Singh Sinsinwar", "authorHandle": "https://www.stopstalk.com/user/profile/suraj279", "addedOn": "2020-12-20 09:53:46", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1794"},
        {"problemName": "CamelCase", "problemLink": "https://www.stopstalk.com/problems?problem_id=17614", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "Raja Ram Sharma", "authorHandle": "https://www.stopstalk.com/user/profile/ArbitCode", "addedOn": "2020-12-18 18:28:48", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1793"},
        {"problemName": "Trip", "problemLink": "https://www.stopstalk.com/problems?problem_id=6842", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Bruh Gemar", "authorHandle": "https://www.stopstalk.com/user/profile/nothank", "addedOn": "2020-11-16 21:36:20", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1790"},
        {"problemName": "Vitaliy and Pie", "problemLink": "https://www.stopstalk.com/problems?problem_id=4454", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Vinay Kushwaha", "authorHandle": "https://www.stopstalk.com/user/profile/iamvinayvk", "addedOn": "2020-10-05 16:06:47", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1787"},
        {"problemName": "B. Go to Jail", "problemLink": "https://www.stopstalk.com/problems?problem_id=81329", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/atcoder_small.png?_rev=None", "authorName": "Harshit Gupta", "authorHandle": "https://www.stopstalk.com/user/profile/harshitgupta", "addedOn": "2020-09-20 16:35:34", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1783"},
        {"problemName": "Vowel Recognition", "problemLink": "https://www.stopstalk.com/problems?problem_id=51229", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "Harshit Gupta", "authorHandle": "https://www.stopstalk.com/user/profile/harshitgupta", "addedOn": "2020-09-20 16:14:06", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1782"},
        {"problemName": "QFUN", "problemLink": "https://www.stopstalk.com/problems?problem_id=80124", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Vishnuvardhan S", "authorHandle": "https://www.stopstalk.com/user/profile/coderag", "addedOn": "2020-08-29 13:59:12", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1776"},
        {"problemName": "The maximum distance", "problemLink": "https://www.stopstalk.com/problems?problem_id=79806", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "Vishnuvardhan S", "authorHandle": "https://www.stopstalk.com/user/profile/coderag", "addedOn": "2020-08-26 09:43:54", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1775"},
        {"problemName": "Rotation", "problemLink": "https://www.stopstalk.com/problems?problem_id=33814", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Jeel Dasvani", "authorHandle": "https://www.stopstalk.com/user/profile/Jeel_Dasvani", "addedOn": "2020-08-24 13:43:45", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1774"},
        {"problemName": "Lets Watch Football", "problemLink": "https://www.stopstalk.com/problems?problem_id=4401", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Pavit Kaur", "authorHandle": "https://www.stopstalk.com/user/profile/Pavit23", "addedOn": "2020-08-18 01:23:04", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1773"},
        {"problemName": "Bad Triangle", "problemLink": "https://www.stopstalk.com/problems?problem_id=79235", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Mehedi Hasan", "authorHandle": "https://www.stopstalk.com/user/profile/King_Aurther", "addedOn": "2020-08-16 18:46:23", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1771"},
        {"problemName": "I AM VERY BUSY", "problemLink": "https://www.stopstalk.com/problems?problem_id=368", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Mehedi Hasan", "authorHandle": "https://www.stopstalk.com/user/profile/King_Aurther", "addedOn": "2020-08-05 10:48:13", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1769"},
        {"problemName": "A Pleasant Stroll", "problemLink": "https://www.stopstalk.com/problems?problem_id=13061", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Nikhil Agrawal", "authorHandle": "https://www.stopstalk.com/user/profile/nikbro12", "addedOn": "2020-08-04 10:23:47", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1765"},
        {"problemName": "A. Air Conditioner", "problemLink": "https://www.stopstalk.com/problems?problem_id=78531", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/atcoder_small.png?_rev=None", "authorName": "Amey Bhavsar", "authorHandle": "https://www.stopstalk.com/user/profile/bhavsar", "addedOn": "2020-08-04 10:04:21", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1763"},
        {"problemName": "B. Distance", "problemLink": "https://www.stopstalk.com/problems?problem_id=78530", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/atcoder_small.png?_rev=None", "authorName": "Amey Bhavsar", "authorHandle": "https://www.stopstalk.com/user/profile/bhavsar", "addedOn": "2020-08-04 10:01:09", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1762"},
        {"problemName": "Vasya the Hipster", "problemLink": "https://www.stopstalk.com/problems?problem_id=4380", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Mehedi Hasan", "authorHandle": "https://www.stopstalk.com/user/profile/705", "addedOn": "2020-08-03 10:14:05", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1761"},
        {"problemName": "Digit Counting", "problemLink": "https://www.stopstalk.com/problems?problem_id=29177", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Anup Ghosh", "authorHandle": "https://www.stopstalk.com/user/profile/ag_bsmrstu", "addedOn": "2020-08-01 23:47:11", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1758"},
        {"problemName": "Frequency of Students", "problemLink": "https://www.stopstalk.com/problems?problem_id=41326", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "Manika Sharma", "authorHandle": "https://www.stopstalk.com/user/profile/manikasharma", "addedOn": "2020-07-27 11:54:30", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1755"},
        {"problemName": "Omkar and Completion", "problemLink": "https://www.stopstalk.com/problems?problem_id=77380", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Md. Sazid Alam", "authorHandle": "https://www.stopstalk.com/user/profile/sazid_alam", "addedOn": "2020-07-13 08:26:51", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1750"},
        {"problemName": "Maximizing XOR", "problemLink": "https://www.stopstalk.com/problems?problem_id=3173", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "sarwarish upadhyay", "authorHandle": "https://www.stopstalk.com/user/profile/sar_1", "addedOn": "2020-07-05 16:06:43", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1746"},
        {"problemName": "INCRDEC", "problemLink": "https://www.stopstalk.com/problems?problem_id=76314", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Nitesh Agrawal", "authorHandle": "https://www.stopstalk.com/user/profile/nitesh_ism", "addedOn": "2020-06-28 19:30:28", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1744"},
        {"problemName": "CHFMOT18", "problemLink": "https://www.stopstalk.com/problems?problem_id=76315", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Zeki Gurbuz", "authorHandle": "https://www.stopstalk.com/user/profile/zekigurbuz", "addedOn": "2020-06-28 01:34:36", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1742"},
        {"problemName": "ZCO14001", "problemLink": "https://www.stopstalk.com/problems?problem_id=36675", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Naman Garg", "authorHandle": "https://www.stopstalk.com/user/profile/naman_203", "addedOn": "2020-06-25 01:29:51", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1741"},
        {"problemName": "Even Array", "problemLink": "https://www.stopstalk.com/problems?problem_id=75768", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Manika Sharma", "authorHandle": "https://www.stopstalk.com/user/profile/manikasharma", "addedOn": "2020-06-22 15:05:42", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1738"},
        {"problemName": "Short Substrings", "problemLink": "https://www.stopstalk.com/problems?problem_id=75769", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Manika Sharma", "authorHandle": "https://www.stopstalk.com/user/profile/manikasharma", "addedOn": "2020-06-22 12:16:17", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1736"},
        {"problemName": "Dragons", "problemLink": "https://www.stopstalk.com/problems?problem_id=3239", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Madhav Koodana Madhu", "authorHandle": "https://www.stopstalk.com/user/profile/k_m_madhav", "addedOn": "2020-06-20 20:19:06", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1734"},
        {"problemName": "Two Arrays And Swaps", "problemLink": "https://www.stopstalk.com/problems?problem_id=72148", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Manika Sharma", "authorHandle": "https://www.stopstalk.com/user/profile/manikasharma", "addedOn": "2020-06-11 12:08:19", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1730"},
        {"problemName": "Adityas Love for Strings", "problemLink": "https://www.stopstalk.com/problems?problem_id=10032", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "SHIVAM JAISWAL", "authorHandle": "https://www.stopstalk.com/user/profile/shivamjaiswal64", "addedOn": "2020-06-05 20:10:15", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1725"},
        {"problemName": "MYSTERY", "problemLink": "https://www.stopstalk.com/problems?problem_id=40131", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "????????????????, ??????", "authorHandle": "https://www.stopstalk.com/user/profile/Uvaish_Zafri", "addedOn": "2020-05-21 14:14:32", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1688"},
        {"problemName": "Maximum Element", "problemLink": "https://www.stopstalk.com/problems?problem_id=4777", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "Suraj Singh Sinsinwar", "authorHandle": "https://www.stopstalk.com/user/profile/suraj279", "addedOn": "2020-05-18 03:58:05", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1682"},
        {"problemName": "Level 3", "problemLink": "https://www.stopstalk.com/problems?problem_id=34950", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "SHIVAM JAISWAL", "authorHandle": "https://www.stopstalk.com/user/profile/shivamjaiswal64", "addedOn": "2020-05-16 10:57:39", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1681"},
        {"problemName": "Level 13", "problemLink": "https://www.stopstalk.com/problems?problem_id=34948", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "SHIVAM JAISWAL", "authorHandle": "https://www.stopstalk.com/user/profile/shivamjaiswal64", "addedOn": "2020-05-16 10:51:12", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1680"},
        {"problemName": "Little Avu and Pattern", "problemLink": "https://www.stopstalk.com/problems?problem_id=35821", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "SHIVAM JAISWAL", "authorHandle": "https://www.stopstalk.com/user/profile/shivamjaiswal64", "addedOn": "2020-05-15 20:33:47", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1679"},
        {"problemName": "Short Name", "problemLink": "https://www.stopstalk.com/problems?problem_id=36103", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "SHIVAM JAISWAL", "authorHandle": "https://www.stopstalk.com/user/profile/shivamjaiswal64", "addedOn": "2020-05-15 20:14:46", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1678"},
        {"problemName": "Search And Rescue", "problemLink": "https://www.stopstalk.com/problems?problem_id=68285", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "SHIVAM JAISWAL", "authorHandle": "https://www.stopstalk.com/user/profile/shivamjaiswal64", "addedOn": "2020-05-15 19:38:17", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1677"},
        {"problemName": "LFIVES", "problemLink": "https://www.stopstalk.com/problems?problem_id=19992", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Yaseen Mollik", "authorHandle": "https://www.stopstalk.com/user/profile/yaseenmollik", "addedOn": "2020-03-29 20:58:55", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1624"},
        {"problemName": "Journey Planning", "problemLink": "https://www.stopstalk.com/problems?problem_id=67204", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "zihad 18", "authorHandle": "https://www.stopstalk.com/user/profile/zihadboss", "addedOn": "2020-03-07 01:56:03", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1618"},
        {"problemName": "ODTPIC", "problemLink": "https://www.stopstalk.com/problems?problem_id=64095", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Shreyansh Gupta", "authorHandle": "https://www.stopstalk.com/user/profile/puns", "addedOn": "2020-02-21 13:42:04", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1617"},
        {"problemName": "Angry Students", "problemLink": "https://www.stopstalk.com/problems?problem_id=63306", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Grim Firefly", "authorHandle": "https://www.stopstalk.com/user/profile/grim_firefly", "addedOn": "2020-02-12 11:55:40", "votes": "4", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1614"},
        {"problemName": "Solve Me First", "problemLink": "https://www.stopstalk.com/problems?problem_id=1769", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "zihad 18", "authorHandle": "https://www.stopstalk.com/user/profile/zihadboss", "addedOn": "2020-01-03 15:58:55", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1605"},
        {"problemName": "Game", "problemLink": "https://www.stopstalk.com/problems?problem_id=3231", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "zihad 18", "authorHandle": "https://www.stopstalk.com/user/profile/zihadboss", "addedOn": "2020-01-03 15:56:34", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1604"},
        {"problemName": "LUCKFOUR", "problemLink": "https://www.stopstalk.com/problems?problem_id=18208", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "zihad 18", "authorHandle": "https://www.stopstalk.com/user/profile/zihadboss", "addedOn": "2019-10-07 04:03:55", "votes": "4", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1600"},
        {"problemName": "Circular Array Rotation", "problemLink": "https://www.stopstalk.com/problems?problem_id=17310", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "Ankit Raj", "authorHandle": "https://www.stopstalk.com/user/profile/coderboy", "addedOn": "2019-09-21 18:46:28", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1597"},
        {"problemName": "Arrays: Left Rotation", "problemLink": "https://www.stopstalk.com/problems?problem_id=24953", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "Ankit Raj", "authorHandle": "https://www.stopstalk.com/user/profile/coderboy", "addedOn": "2019-08-28 19:06:44", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1594"},
        {"problemName": "Shortest Cycle", "problemLink": "https://www.stopstalk.com/problems?problem_id=58070", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Iqbal Hossain", "authorHandle": "https://www.stopstalk.com/user/profile/IHR57", "addedOn": "2019-08-23 10:41:26", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1591"},
        {"problemName": "CHEFRRUN", "problemLink": "https://www.stopstalk.com/problems?problem_id=20375", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Amit Sarker", "authorHandle": "https://www.stopstalk.com/user/profile/Peregrine_Falcon", "addedOn": "2019-08-22 04:06:10", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1590"},
        {"problemName": "Monk and the Islands", "problemLink": "https://www.stopstalk.com/problems?problem_id=22795", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "Ashutosh Singh", "authorHandle": "https://www.stopstalk.com/user/profile/destroyerguy", "addedOn": "2019-08-15 11:53:38", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1589"},
        {"problemName": "New Year Transportation", "problemLink": "https://www.stopstalk.com/problems?problem_id=1359", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Ashutosh Singh", "authorHandle": "https://www.stopstalk.com/user/profile/destroyerguy", "addedOn": "2019-08-14 23:57:33", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1588"},
        {"problemName": "Diameter Minimization", "problemLink": "https://www.stopstalk.com/problems?problem_id=44237", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerrank_small.png?_rev=20201225170526", "authorName": "IAN CARSON", "authorHandle": "https://www.stopstalk.com/user/profile/iancarson", "addedOn": "2019-07-21 21:13:57", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1578"},
        {"problemName": "Adjacent Bit Counts", "problemLink": "https://www.stopstalk.com/problems?problem_id=706", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Aditya Soni", "authorHandle": "https://www.stopstalk.com/user/profile/adist98", "addedOn": "2019-07-08 19:20:09", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1576"},
        {"problemName": "Keanu Reeves", "problemLink": "https://www.stopstalk.com/problems?problem_id=57172", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Md.Nazmul Hossin", "authorHandle": "https://www.stopstalk.com/user/profile/Nazmul_Hossin", "addedOn": "2019-07-06 09:41:49", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1575"},
        {"problemName": "Cookies", "problemLink": "https://www.stopstalk.com/problems?problem_id=1111", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Khushal Agarwal", "authorHandle": "https://www.stopstalk.com/user/profile/khushalagarwal", "addedOn": "2019-06-27 22:35:21", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1572"},
        {"problemName": "Two-gram", "problemLink": "https://www.stopstalk.com/problems?problem_id=46730", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Khushal Agarwal", "authorHandle": "https://www.stopstalk.com/user/profile/khushalagarwal", "addedOn": "2019-06-23 00:13:08", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1567"},
        {"problemName": "Cakeminator", "problemLink": "https://www.stopstalk.com/problems?problem_id=1647", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Khushal Agarwal", "authorHandle": "https://www.stopstalk.com/user/profile/khushalagarwal", "addedOn": "2019-06-22 23:31:43", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1566"},
        {"problemName": "Maximum Increase", "problemLink": "https://www.stopstalk.com/problems?problem_id=17667", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Khushal Agarwal", "authorHandle": "https://www.stopstalk.com/user/profile/khushalagarwal", "addedOn": "2019-06-22 22:12:58", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1565"},
        {"problemName": "Friends Meeting", "problemLink": "https://www.stopstalk.com/problems?problem_id=45079", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Khushal Agarwal", "authorHandle": "https://www.stopstalk.com/user/profile/khushalagarwal", "addedOn": "2019-06-19 17:58:46", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1563"},
        {"problemName": "Buying Apples!", "problemLink": "https://www.stopstalk.com/problems?problem_id=214", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Anurag Phadnis", "authorHandle": "https://www.stopstalk.com/user/profile/realalphastar", "addedOn": "2019-06-19 11:30:18", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1562"},
        {"problemName": "The Doors", "problemLink": "https://www.stopstalk.com/problems?problem_id=54743", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Khushal Agarwal", "authorHandle": "https://www.stopstalk.com/user/profile/khushalagarwal", "addedOn": "2019-06-18 16:30:31", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1561"},
        {"problemName": "Tree and Queries", "problemLink": "https://www.stopstalk.com/problems?problem_id=2377", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Amit Sarker", "authorHandle": "https://www.stopstalk.com/user/profile/Peregrine_Falcon", "addedOn": "2019-06-17 18:30:07", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1560"},
        {"problemName": "R2D2 and Droid Army", "problemLink": "https://www.stopstalk.com/problems?problem_id=3043", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Amit Sarker", "authorHandle": "https://www.stopstalk.com/user/profile/Peregrine_Falcon", "addedOn": "2019-06-16 10:51:16", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1558"},
        {"problemName": "Array Transformer", "problemLink": "https://www.stopstalk.com/problems?problem_id=32467", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Amit Sarker", "authorHandle": "https://www.stopstalk.com/user/profile/Peregrine_Falcon", "addedOn": "2019-06-14 11:54:20", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1556"},
        {"problemName": "Its all about magic!", "problemLink": "https://www.stopstalk.com/problems?problem_id=8865", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "Manish Kumar Verma", "authorHandle": "https://www.stopstalk.com/user/profile/mkv", "addedOn": "2019-06-07 14:15:29", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1551"},
        {"problemName": "IEMCO7F", "problemLink": "https://www.stopstalk.com/problems?problem_id=55596", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Md Shahbaz Alam", "authorHandle": "https://www.stopstalk.com/user/profile/shah_entrance", "addedOn": "2019-05-27 09:03:06", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1550"},
        {"problemName": "Alice, Bob and Chocolate", "problemLink": "https://www.stopstalk.com/problems?problem_id=22378", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-25 21:51:05", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1549"},
        {"problemName": "PFAST Inc.", "problemLink": "https://www.stopstalk.com/problems?problem_id=5667", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-23 17:17:15", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1548"},
        {"problemName": "SPOJ Custom Test", "problemLink": "https://www.stopstalk.com/problems?problem_id=24644", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Abu Noman Md Sakib", "authorHandle": "https://www.stopstalk.com/user/profile/anms_pro", "addedOn": "2019-05-18 03:49:56", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1546"},
        {"problemName": "MCO16403", "problemLink": "https://www.stopstalk.com/problems?problem_id=34966", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-16 23:46:40", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1544"},
        {"problemName": "Woodcutters", "problemLink": "https://www.stopstalk.com/problems?problem_id=4450", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-16 20:33:11", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1543"},
        {"problemName": "Hard problem", "problemLink": "https://www.stopstalk.com/problems?problem_id=20146", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-16 19:21:14", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1542"},
        {"problemName": "Chain Reaction", "problemLink": "https://www.stopstalk.com/problems?problem_id=2489", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-16 16:19:39", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1541"},
        {"problemName": "Boredom", "problemLink": "https://www.stopstalk.com/problems?problem_id=666", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-16 11:14:15", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1540"},
        {"problemName": "Cyclic Components", "problemLink": "https://www.stopstalk.com/problems?problem_id=46729", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-15 21:39:48", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1539"},
        {"problemName": "1001. Reverse Root", "problemLink": "https://www.stopstalk.com/problems?problem_id=48544", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/timus_small.png?_rev=None", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-15 21:36:13", "votes": "3", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1538"},
        {"problemName": "Find Maximum", "problemLink": "https://www.stopstalk.com/problems?problem_id=4308", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codeforces_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-15 03:17:05", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1536"},
        {"problemName": "WTBTR", "problemLink": "https://www.stopstalk.com/problems?problem_id=55841", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-13 19:03:40", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1535"},
        {"problemName": "MAXSEGM", "problemLink": "https://www.stopstalk.com/problems?problem_id=38585", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Harsh Raj", "authorHandle": "https://www.stopstalk.com/user/profile/harshraj22", "addedOn": "2019-05-11 13:46:06", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1533"},
        {"problemName": "Goldbach and Euler", "problemLink": "https://www.stopstalk.com/problems?problem_id=28723", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Tashreef Muhammad", "authorHandle": "https://www.stopstalk.com/user/profile/UnknownDragneel", "addedOn": "2019-04-13 11:15:58", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1528"},
        {"problemName": "IEMCHM15", "problemLink": "https://www.stopstalk.com/problems?problem_id=53133", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-04-01 00:00:33", "votes": "8", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1523"},
        {"problemName": "IEMCHM14", "problemLink": "https://www.stopstalk.com/problems?problem_id=53139", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-04-01 00:00:21", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1522"},
        {"problemName": "IEMCHM13", "problemLink": "https://www.stopstalk.com/problems?problem_id=53033", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-04-01 00:00:11", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1521"},
        {"problemName": "CONSESNK", "problemLink": "https://www.stopstalk.com/problems?problem_id=38007", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-04-01 00:00:07", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1520"},
        {"problemName": "IEMCHM12", "problemLink": "https://www.stopstalk.com/problems?problem_id=53034", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-04-01 00:00:03", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1519"},
        {"problemName": "IEMCHM11", "problemLink": "https://www.stopstalk.com/problems?problem_id=52774", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:59:54", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1518"},
        {"problemName": "IEMCHM10", "problemLink": "https://www.stopstalk.com/problems?problem_id=52775", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:59:44", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1517"},
        {"problemName": "IEMCHEM9", "problemLink": "https://www.stopstalk.com/problems?problem_id=52772", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:59:35", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1516"},
        {"problemName": "IEMCHEM8", "problemLink": "https://www.stopstalk.com/problems?problem_id=52773", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:59:26", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1515"},
        {"problemName": "IEMCHEM7", "problemLink": "https://www.stopstalk.com/problems?problem_id=52776", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:59:16", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1514"},
        {"problemName": "IEMCHEM6", "problemLink": "https://www.stopstalk.com/problems?problem_id=52777", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:59:05", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1513"},
        {"problemName": "FBFRW1", "problemLink": "https://www.stopstalk.com/problems?problem_id=17775", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:58:31", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1510"},
        {"problemName": "CDMU02", "problemLink": "https://www.stopstalk.com/problems?problem_id=24012", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:58:18", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1509"},
        {"problemName": "IDCMSG", "problemLink": "https://www.stopstalk.com/problems?problem_id=21087", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:58:09", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1508"},
        {"problemName": "IEMCHEM2", "problemLink": "https://www.stopstalk.com/problems?problem_id=52780", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:57:59", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1507"},
        {"problemName": "Sorting is easy", "problemLink": "https://www.stopstalk.com/problems?problem_id=12579", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:56:38", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1500"},
        {"problemName": "Easy Sorting", "problemLink": "https://www.stopstalk.com/problems?problem_id=7001", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/spoj_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:56:21", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1499"},
        {"problemName": "SORT", "problemLink": "https://www.stopstalk.com/problems?problem_id=19633", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:56:10", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1498"},
        {"problemName": "HOLES2", "problemLink": "https://www.stopstalk.com/problems?problem_id=23987", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:55:59", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1497"},
        {"problemName": "SORT4", "problemLink": "https://www.stopstalk.com/problems?problem_id=23015", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:55:48", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1496"},
        {"problemName": "Lotto", "problemLink": "https://www.stopstalk.com/problems?problem_id=29143", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:55:34", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1495"},
        {"problemName": "Ingenuous Cubrency", "problemLink": "https://www.stopstalk.com/problems?problem_id=29209", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:55:23", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1493"},
        {"problemName": "Integer Inquiry", "problemLink": "https://www.stopstalk.com/problems?problem_id=28585", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:55:11", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1492"},
        {"problemName": "Car", "problemLink": "https://www.stopstalk.com/problems?problem_id=28881", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:54:57", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1491"},
        {"problemName": "Andys First Dictionary", "problemLink": "https://www.stopstalk.com/problems?problem_id=28768", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:54:46", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1490"},
        {"problemName": "Adding Reversed Numbers", "problemLink": "https://www.stopstalk.com/problems?problem_id=29058", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:54:34", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1489"},
        {"problemName": "500!", "problemLink": "https://www.stopstalk.com/problems?problem_id=28756", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:54:21", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1488"},
        {"problemName": "Dividing coins", "problemLink": "https://www.stopstalk.com/problems?problem_id=29135", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:54:09", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1487"},
        {"problemName": "Sending email", "problemLink": "https://www.stopstalk.com/problems?problem_id=28717", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:53:19", "votes": "3", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1486"},
        {"problemName": "Knight Moves", "problemLink": "https://www.stopstalk.com/problems?problem_id=28698", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:53:07", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1485"},
        {"problemName": "Factorial! You Must be Kidding!!!", "problemLink": "https://www.stopstalk.com/problems?problem_id=28781", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:52:54", "votes": "3", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1484"},
        {"problemName": "Hartals", "problemLink": "https://www.stopstalk.com/problems?problem_id=28691", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:52:41", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1483"},
        {"problemName": "Throwing cards away I", "problemLink": "https://www.stopstalk.com/problems?problem_id=28882", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:52:26", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1482"},
        {"problemName": "Longest Common Subsequence", "problemLink": "https://www.stopstalk.com/problems?problem_id=28764", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:52:14", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1481"},
        {"problemName": "Zero or One", "problemLink": "https://www.stopstalk.com/problems?problem_id=29243", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:52:03", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1480"},
        {"problemName": "Zeros and Ones", "problemLink": "https://www.stopstalk.com/problems?problem_id=28677", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:51:51", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1479"},
        {"problemName": "Vitos Family", "problemLink": "https://www.stopstalk.com/problems?problem_id=29120", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:51:38", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1478"},
        {"problemName": "Multiple of 17", "problemLink": "https://www.stopstalk.com/problems?problem_id=28862", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:51:23", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1477"},
        {"problemName": "Ecological Bin Packing", "problemLink": "https://www.stopstalk.com/problems?problem_id=28861", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:51:11", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1476"},
        {"problemName": "Etruscan Warriors Never Play Chess", "problemLink": "https://www.stopstalk.com/problems?problem_id=29179", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:50:55", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1475"},
        {"problemName": "Robot Instructions", "problemLink": "https://www.stopstalk.com/problems?problem_id=28822", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:50:40", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1474"},
        {"problemName": "Prime Factors", "problemLink": "https://www.stopstalk.com/problems?problem_id=29048", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:50:27", "votes": "3", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1473"},
        {"problemName": "Add All", "problemLink": "https://www.stopstalk.com/problems?problem_id=28654", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:50:14", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1472"},
        {"problemName": "Palindromes", "problemLink": "https://www.stopstalk.com/problems?problem_id=29229", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:50:00", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1471"},
        {"problemName": "Hardwood Species", "problemLink": "https://www.stopstalk.com/problems?problem_id=29284", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:49:35", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1469"},
        {"problemName": "ID Codes", "problemLink": "https://www.stopstalk.com/problems?problem_id=29248", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:49:19", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1468"},
        {"problemName": "The Lazy Lumberjacks", "problemLink": "https://www.stopstalk.com/problems?problem_id=29302", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:49:05", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1467"},
        {"problemName": "Tariff Plan", "problemLink": "https://www.stopstalk.com/problems?problem_id=28772", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:48:50", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1466"},
        {"problemName": "You can say 11", "problemLink": "https://www.stopstalk.com/problems?problem_id=28858", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:48:36", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1465"},
        {"problemName": "All in All", "problemLink": "https://www.stopstalk.com/problems?problem_id=28964", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:48:20", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1464"},
        {"problemName": "Count the factors", "problemLink": "https://www.stopstalk.com/problems?problem_id=28986", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:48:05", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1463"},
        {"problemName": "Numbering Roads", "problemLink": "https://www.stopstalk.com/problems?problem_id=29137", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:47:32", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1462"},
        {"problemName": "Love Calculator", "problemLink": "https://www.stopstalk.com/problems?problem_id=29070", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:36:46", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1461"},
        {"problemName": "Goldbachs Conjecture (II)", "problemLink": "https://www.stopstalk.com/problems?problem_id=28758", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:36:29", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1460"},
        {"problemName": "The Playboy Chimp", "problemLink": "https://www.stopstalk.com/problems?problem_id=29107", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:35:27", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1459"},
        {"problemName": "The jackpot", "problemLink": "https://www.stopstalk.com/problems?problem_id=28844", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:35:11", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1458"},
        {"problemName": "Mother bear", "problemLink": "https://www.stopstalk.com/problems?problem_id=28686", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:34:48", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1457"},
        {"problemName": "Google is Feeling Lucky", "problemLink": "https://www.stopstalk.com/problems?problem_id=29028", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:34:30", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1456"},
        {"problemName": "Prime Words", "problemLink": "https://www.stopstalk.com/problems?problem_id=28842", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:34:06", "votes": "3", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1455"},
        {"problemName": "Find the Telephone", "problemLink": "https://www.stopstalk.com/problems?problem_id=28936", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:33:49", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1454"},
        {"problemName": "Simply Emirp", "problemLink": "https://www.stopstalk.com/problems?problem_id=29117", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:33:22", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1453"},
        {"problemName": "Feynman", "problemLink": "https://www.stopstalk.com/problems?problem_id=28934", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:32:49", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1452"},
        {"problemName": "Newspaper", "problemLink": "https://www.stopstalk.com/problems?problem_id=28555", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:32:37", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1451"},
        {"problemName": "Where is the Marble?", "problemLink": "https://www.stopstalk.com/problems?problem_id=29198", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/uva_small.png?_rev=20201225170526", "authorName": "Sandeep Pradhan", "authorHandle": "https://www.stopstalk.com/user/profile/Sandeep_Pradhan", "addedOn": "2019-03-31 23:32:01", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1450"},
        {"problemName": "JAGAM", "problemLink": "https://www.stopstalk.com/problems?problem_id=50295", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Saumya Acharya", "authorHandle": "https://www.stopstalk.com/user/profile/saumya1729", "addedOn": "2019-03-31 23:05:25", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1449"},
        {"problemName": "CONSESNK", "problemLink": "https://www.stopstalk.com/problems?problem_id=38007", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Saumya Acharya", "authorHandle": "https://www.stopstalk.com/user/profile/saumya1729", "addedOn": "2019-03-31 23:04:03", "votes": "0", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1448"},
        {"problemName": "Polynomial sign", "problemLink": "https://www.stopstalk.com/problems?problem_id=42111", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 20:17:03", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1429"},
        {"problemName": "CHEFWORK", "problemLink": "https://www.stopstalk.com/problems?problem_id=46292", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 19:58:37", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1424"},
        {"problemName": "DAY 1 - Future Lights", "problemLink": "https://www.stopstalk.com/problems?problem_id=44122", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/hackerearth_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 19:55:03", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1421"},
        {"problemName": "COMB4", "problemLink": "https://www.stopstalk.com/problems?problem_id=52795", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 19:54:17", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1420"},
        {"problemName": "BINIM2", "problemLink": "https://www.stopstalk.com/problems?problem_id=50608", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Saumya Acharya", "authorHandle": "https://www.stopstalk.com/user/profile/saumya1729", "addedOn": "2019-03-31 19:50:58", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1416"},
        {"problemName": "ANWCC01", "problemLink": "https://www.stopstalk.com/problems?problem_id=52925", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 19:48:58", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1414"},
        {"problemName": "HCNTST", "problemLink": "https://www.stopstalk.com/problems?problem_id=52970", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 19:46:25", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1410"},
        {"problemName": "ANKSPCL", "problemLink": "https://www.stopstalk.com/problems?problem_id=52968", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 19:45:25", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1409"},
        {"problemName": "PPDAY", "problemLink": "https://www.stopstalk.com/problems?problem_id=53755", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 19:30:55", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1398"},
        {"problemName": "RICHMICH", "problemLink": "https://www.stopstalk.com/problems?problem_id=53874", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 19:27:35", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1394"},
        {"problemName": "J7", "problemLink": "https://www.stopstalk.com/problems?problem_id=17824", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 19:24:26", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1390"},
        {"problemName": "SCET01", "problemLink": "https://www.stopstalk.com/problems?problem_id=54788", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 19:18:22", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1385"},
        {"problemName": "CHEFLBW", "problemLink": "https://www.stopstalk.com/problems?problem_id=53920", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 19:14:07", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1384"},
        {"problemName": "CR194", "problemLink": "https://www.stopstalk.com/problems?problem_id=54120", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 18:59:51", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1375"},
        {"problemName": "CSIXIERL", "problemLink": "https://www.stopstalk.com/problems?problem_id=23993", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 18:51:20", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1369"},
        {"problemName": "COEN03", "problemLink": "https://www.stopstalk.com/problems?problem_id=54196", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Mohit Gholake", "authorHandle": "https://www.stopstalk.com/user/profile/gholakemohit", "addedOn": "2019-03-31 18:50:19", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1368"},
        {"problemName": "VWL", "problemLink": "https://www.stopstalk.com/problems?problem_id=54443", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 18:42:00", "votes": "2", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1367"},
        {"problemName": "FLOW018", "problemLink": "https://www.stopstalk.com/problems?problem_id=18121", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Rumman Sadik", "authorHandle": "https://www.stopstalk.com/user/profile/rummansadik", "addedOn": "2019-03-31 18:38:46", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1365"},
        {"problemName": "LIKECS03", "problemLink": "https://www.stopstalk.com/problems?problem_id=40825", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "AMAN SINGH", "authorHandle": "https://www.stopstalk.com/user/profile/aksingh007", "addedOn": "2019-03-31 18:32:10", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1363"},
        {"problemName": "FLOW017", "problemLink": "https://www.stopstalk.com/problems?problem_id=18478", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Rumman Sadik", "authorHandle": "https://www.stopstalk.com/user/profile/rummansadik", "addedOn": "2019-03-31 18:29:08", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1362"},
        {"problemName": "REMISS", "problemLink": "https://www.stopstalk.com/problems?problem_id=18294", "siteIcon": "https://www.stopstalk.com/stopstalk/static/images/codechef_small.png?_rev=20201225170526", "authorName": "Rumman Sadik", "authorHandle": "https://www.stopstalk.com/user/profile/rummansadik", "addedOn": "2019-03-31 18:26:11", "votes": "1", "editorialLink": "https://www.stopstalk.com/problems/read_editorial/1360"}
    ]
    );
} );
